apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-example-app
spec:
  replicas: 2 # You can adjust the number of replicas
  selector:
    matchLabels:
      app: argocd-example-app
  template:
    metadata:
      labels:
        app: argocd-example-app
    spec:
      containers:
      - name: j-cinema-v2-container
        image: us-central1-docker.pkg.dev/cool-new-project-432118/christos-docker-virtual-repo/jazz-to-tech-v2:latest
        ports:
        - containerPort: 5000 # Assuming your app runs on port 3000
