apiVersion: v1
kind: Service
metadata:
  name: argocd-example-app-service
spec:
  type: NodePort
  selector:
    app: argocd-example-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31000 
